server:
  port: 2021
spring:
  application:
    name: identity-service
  config:
    import: "optional:configserver:http://localhost:2222"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
