server:
  port: 2020

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatically creates routes based on Service Names!
      routes:
        # Route 1: Identity Service
        - id: identity-service
          uri: lb://IDENTITY-SERVICE  # 'lb' means Load Balanced
          predicates:
            - Path=/auth/**

        # Route 2: Job Service
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
          filters:
            - AuthenticationFilter

        # Route 3: Profile Service
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profiles/**

        # Route 4: Application Service
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/applications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}